[package]
name = "fictui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_ratatui = "0.6.4"
clap = { version = "4.5.21", features = ["derive"] }
ratatui = "0.29.0"
tui-input = "0.11.1"
