[package]
name = "fictui_core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
rusqlite = { version = "0.32.0", features = ["bundled"] }
rusqlite_migration = "1.3.1"
